### ISSUE TITLE
Fail to run the command `npm run env:init`

### ISSUE THREAD

**Issue by zhangjiale-64** [pinecone-io/pinecone-rag-demo-azd#3]
**Describe the issue**:
Run command `npm run env:init` in Windows (bash) ,Devcontainer and Codespaces, get error as follow:
![image](https://github.com/pinecone-io/pinecone-rag-demo-azd/assets/141405558/33ad897b-d37a-4fb4-83ca-de0bc4f52b35)

**Repro Steps**:

1. Run `git clone https://github.com/pinecone-io/pinecone-rag-demo-azd.git`
2. Run `cd pinecone-rag-demo-azd`
3. Run `npm i`
4. Run `npm run env:init`

**Environments**:

- azd version: 1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)
- os: Windows, DevContainer and codespace

**Expected behavior**:

Running the command `npm run env:init` can successfully create the ".env.local" file.

@hemarina and @cwaddingham for notification.

**Comment by cwaddingham** [comment]
@zhangjiale-64 please be sure you have set the required environment variables and secrets, either in your local environment or in your Github project. Please see the README.md for the full list of required variables.

**Comment by zhangjiale-64** [comment]
> @zhangjiale-64 please be sure you have set the required environment variables and secrets, either in your local environment or in your Github project. Please see the README.md for the full list of required variables.

@cwaddingham please update the README.md to include all required environment variables and resources, such as Pinecone and OpenAI services. Include links to relevant documentation or registration pages to assist users in setting up. After I have configured the required environment variables, run the `azd deploy` command, get error as follow:
![image](https://github.com/pinecone-io/pinecone-rag-demo-azd/assets/141405558/dc78f401-cac4-4293-a5d9-b3799db40b19)
![image](https://github.com/pinecone-io/pinecone-rag-demo-azd/assets/141405558/3b061354-b4e5-4afb-8db0-dae90abb473d)

**Repro Steps**:

1. Run `git clone https://github.com/pinecone-io/pinecone-rag-demo-azd.git`
2. Run `cd pinecone-rag-demo-azd`
3. Run `npm i`
4. Run `npm run env:init`
5. Run `azd auth login`
6. Run `azd provision`
7. Run `azd deploy`

**Environments**:

- azd version: 1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)
- os: Windows, DevContainer and codespace

**Comment by cwaddingham** [comment]
I've added the environment variables to the README.md file, please review, set in your local environment or fork, and try again. 

For convenience they are:
   * `PINECONE_API_KEY={your Pinecone API key}`
     * You can retrieve this from your [Pinecone project's list of API keys](https://app.pinecone.io/-/projects/-/keys).
   * `OPENAI_API_KEY={your OpenAI API key}`
     * This can be retrieved from your [OpenAI project](https://platform.openai.com/api-keys).
   * `PINECONE_REGION={your Pinecone region}`
     * The region your index is hosted in, or will be created in.
   * `PINECONE_INDEX={your index name}`
     * Defaults to `pinecone-rag-demo-azd`.
   * `AZURE_ENV_NAME=prod`
     * This doesn't need to match the GitHub Environment name and because it is used when generating Azure resource names it's a good idea to keep it short
   * `AZURE_TENANT_ID={tenant_id}`
     * Replace `{tenant_id}` with your Tenant's `Tenant ID`
   * `AZURE_SUBSCRIPTION_ID={subscription_id}`
     * Replace `{subscription_id}` with your Subscription's `Subscription ID`
   * `AZURE_CLIENT_ID={service_principal_id}`
     * Replace `{service_principal_id}` with your Service principal's `Application ID`
   * `AZURE_LOCATION={location_name}`
     * Replace `{location_name}` with your desired region name
     * You can see a list of region names using the Azure CLI: `az account list-locations -o table`
   * `SERVICE_WEB_CONTAINER_MIN_REPLICAS=1`
     * Assuming that you don't want your production app to scale to zero

**Comment by gkulin** [comment]
@zhangjiale-64 @v-xuto were you able to successfully `run npm run env:init` after configuring the required env variables Cory provided?

**Comment by zhangjiale-64** [comment]
> @zhangjiale-64 @v-xuto were you able to successfully `run npm run env:init` after configuring the required env variables Cory provided?

Sorry for the delayed response. This issue has been fixed and I will close it.
