### ISSUE TITLE
Link error in the README

### ISSUE THREAD

**Issue by zhangjiale-64** [pinecone-io/pinecone-rag-demo-azd#4]
**Describe the issue:**
 
Link error in the README of `Codespace` and `Dev Container`.
 
![image](https://github.com/pinecone-io/pinecone-rag-demo-azd/assets/141212663/7c78b0e3-ee84-4f3a-8d27-f232cc6f753b)
 
**Suggestion:**
 
Change links to : 
`Codespace` : [https://codespaces.new/pinecone-io/pinecone-rag-demo-azd](https://codespaces.new/pinecone-io/pinecone-rag-demo-azd)
`Dev Container` : [https://vscode.dev/redirect?url=vscode://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/pinecone-io/pinecone-rag-demo-azd](https://vscode.dev/redirect?url=vscode://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/pinecone-io/pinecone-rag-demo-azd)

@hemarina and @cwaddingham for notification.

**Comment by cwaddingham** [comment]
Fixed.
